Piranha.VNext/Core/Piranha.Manager/Areas/Manager/Controllers/PageMgrController.cs
/*
 * Copyright (c) 2014-2015 Håkan Edling
 *
 * This software may be modified and distributed under the terms
 * of the MIT license.  See the LICENSE file for details.
 * 
 * http://github.com/piranhacms/piranha.vnext
 * 
 */

using System;
using System.Linq;
using System.Web.Mvc;
using Piranha.Manager.Models.Page;

namespace Piranha.Areas.Manager.Controllers
{
	/// <summary>
	/// Controller for managing pages.
	/// </summary>
	[Authorize]
	[RouteArea("Manager", AreaPrefix="manager")]
    public class PageMgrController : ManagerController
    {
		/// <summary>
		/// Gets a list of the currently available pages
		/// </summary>
		/// <returns></returns>
		[Route("pages/{slug?}")]
		public ActionResult List(string slug = null) {
			return View(ListModel.Get(slug));
		}

		[Route("page/add/{type}")]
		public ActionResult Add(string type) {
			var model = new EditModel(api, type);

			ViewBag.Title = String.Format(Piranha.Manager.Resources.Page.AddTitle, model.TypeName);
			return View("Edit", model);
		}

		/// <summary>
		/// Gets the edit view for a new or existing page.
		/// </summary>
		/// <param name="id">The optional id</param>
		/// <returns>The view result</returns>
		[Route("page/edit/{id:Guid}")]
		public ActionResult Edit(Guid id) {
			var model = EditModel.GetById(api, id);

			ViewBag.Title = Piranha.Manager.Resources.Page.EditTitle;
			ViewBag.SubTitle = model.Published.HasValue ? 
				((model.Published.Value > DateTime.Now ? "Schedueled: " : "Published: ") + model.Published.Value.ToString("yyyy-MM-dd")) : "Unpublished";

			return View(model);
		}

		/// <summary>
		/// Saves the given page model.
		/// </summary>
		/// <param name="model">The model</param>
		/// <returns>The redirect result</returns>
		[HttpPost]
		[Route("page/save")]
		[ValidateInput(false)]
		[ValidateAntiForgeryToken]
		public ActionResult Save(EditModel model) {
			if (ModelState.IsValid) {
				model.Save(api);
				IsSaved = true;
				return RedirectToAction("Edit", new { id = model.Id });
			}
			if (model.Id.HasValue)
				ViewBag.Title = Piranha.Manager.Resources.Page.EditTitle;
			else ViewBag.Title = String.Format(Piranha.Manager.Resources.Page.AddTitle, model.TypeName);

			return View("Edit", model);
		}

		/// <summary>
		/// Deletes the page with the given id.
		/// </summary>
		/// <param name="id">The unique id</param>
		/// <returns>The redirect result</returns>
		[Route("page/delete/{id:Guid}")]
		public ActionResult Delete(Guid id) {
			api.Pages.Remove(id);
			api.SaveChanges();

			return RedirectToAction("List");
		}
	}
}

Piranha.VNext/Core/Piranha.Manager/Areas/Manager/Views/PageMgr/Edit.cshtml
@model Piranha.Manager.Models.Page.EditModel

@section head {
    <style type="text/css">
        #Excerpt {
            height: 198px;
        }
    </style>
}

@section script {
    @Html.Partial("Partial/Editor")

    <script type="text/javascript">
        $(document).ready(function () {
            // Focus the first input box
            $('#Title').focus();
        });

        // Set submit action to publish
        $(document).on('click', '#submit-publish', function () {
            $('#Action').val('@((int)Piranha.Manager.Models.Post.EditModel.SubmitAction.Publish)');
            $('form').submit();
        });

        // Set submit action to upublish
        $(document).on('click', '#submit-unpublish', function () {
            $('#Action').val('@((int)Piranha.Manager.Models.Post.EditModel.SubmitAction.Unpublish)');
            $('form').submit();
        });
    </script>
}

@using (var form = Html.BeginForm("Save", "PageMgr", FormMethod.Post, new { @class = "form", @role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.TypeId)
    @Html.HiddenFor(m => m.TypeName)
    @Html.HiddenFor(m => m.Action)
    @Html.HiddenFor(m => m.SortOrder)

    <div class="row">
        <!-- Actions -->
        <div class="col-sm-12 buttons">
            <!-- Settings -->
            <div class="btn-group">
                <button type="button" class="btn btn-labeled btn-primary" data-toggle="modal" data-target="#mdSettings">
                    <span class="btn-label">
                        <i class="glyphicon glyphicon-cog"></i>
                    </span>
                    @Piranha.Manager.Resources.Global.Settings
                </button>
            </div>

            <!-- Actions -->
            <div class="btn-group">
                <button type="submit" class="btn btn-labeled btn-success">
                    <span class="btn-label">
                        <i class="glyphicon glyphicon-ok"></i>
                    </span>
                    @if (Model.Published.HasValue)
                    {
                        @Piranha.Manager.Resources.Page.UpdatePost
                    }
                    else
                    {
                        @Piranha.Manager.Resources.Global.SaveDraft
                    }
                </button>
                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                    @if (Model.Published.HasValue)
                    {
                        <li><a id="submit-unpublish" href="#">Unpublish</a></li>
                    }
                    else
                    {
                        <li><a id="submit-publish" href="#">Publish now</a></li>
                    }
                    <li class="divider"></li>
                    <li><a href="@Url.Action("Delete", new { @id = Model.Id })">Delete post</a></li>
                </ul>
            </div>
        </div>

        <div class="col-sm-12">
            <div class="form-group">
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control title", @placeholder = "Your page title" })
                @Html.ValidationMessageFor(m => m.Title)
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">@Piranha.Manager.Resources.Global.Information</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        @Html.TextAreaFor(m => m.Excerpt, new { @rows = 7, @class = "form-control count-me", @placeholder = "Short excerpt" })
                        <p><span>@(Model.Excerpt != null ? Model.Excerpt.Length : 0)</span>/512 characters</p>
                        @Html.ValidationMessageFor(m => m.Excerpt)
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        @Html.DropDownListFor(m => m.AuthorId, Model.Authors, "", new { @class = "form-control meta", @placeholer = "Select author" })
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Keywords, new { @class = "form-control meta", @placeholder = "Meta keywords" })
                        @Html.ValidationMessageFor(m => m.Keywords)
                    </div>
                    <div class="form-group">
                        @Html.TextAreaFor(m => m.Description, new { @rows = 4, @class = "form-control meta count-me", @placeholder = "Meta description" })
                        <p class="charcount"><span>@(Model.Description != null ? Model.Description.Length : 0)</span>/255 characters</p>
                        @Html.ValidationMessageFor(m => m.Description)
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default" role="tabpanel">
        <div class="panel-heading">
            <h3 class="panel-title">Properties</h3>
        </div>
        <div class="panel-body">
            @if (Model.Properties != null)
            {
                for (int i = 0; i < Model.Properties.Count; i++)
                {
                    @Html.EditorFor(m => m.Properties[i], "Property");
                }
            } 
        </div>
    </div>

    <div class="panel panel-default" role="tabpanel">
        <div class="panel-heading">
            <div role="tablist">

            </div>
            <div class="btn-group pull-right" style="display:none">
                <button type="button" class="btn btn-sm btn-labeled btn-info">
                    <span class="btn-label">
                        <i class="glyphicon glyphicon-paperclip"></i>
                    </span>
                    Attachments
                </button>
            </div>
            <button class="btn btn-sm btn-primary pull-right">Main body</button>
            <button class="btn btn-sm btn-primary pull-right" style="display:none">Excerpt</button>
            <h3 class="panel-title">Content</h3>
        </div>
        <div class="panel-body" style="padding:0">
            <div class="form-group" style="border:0">
                @Html.TextAreaFor(m => m.Body, new { @rows = 14, @class = "form-control editor" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
        </div>
    </div>

	<!-- Settings modal -->
    <div class="modal fade" id="mdSettings" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Post settings</h4>
                </div>
                <div class="modal-body">
                    @Html.LabelFor(m => m.Slug, Piranha.Manager.Resources.Global.Slug)
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Slug, new { @class = "form-control meta", @placeholder = "A slug will be generated automatically" })
                    </div>
                    @Html.LabelFor(m => m.Route, Piranha.Manager.Resources.Global.Route)
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Route, new { @class = "form-control meta", @placeholder = "Add optional route" })
                    </div>
                    @Html.LabelFor(m => m.View, Piranha.Manager.Resources.Global.View)
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.View, new { @class = "form-control meta", @placeholder = "Add optional view" })
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">@Piranha.Manager.Resources.Global.Ok</button>
                </div>
            </div>
        </div>
    </div>
}

Piranha.VNext/Core/Piranha.Manager/Areas/Manager/Views/PageMgr/List.cshtml
@model Piranha.Manager.Models.Page.ListModel
@{
	ViewBag.Title = Piranha.Manager.Resources.Page.ListTitle;
}
@section script {
	<script type="text/javascript">
		var options = {
			valueNames: ['page-title', 'page-type', 'page-updated', 'page-created']
		};
		var pageList = new List('page-list', options);
	</script>
}

<div class="row">
	<div class="col-sm-12 @(Model.PageTypes.Count == 1 ? "buttons" : "")">
		@if (Model.PageTypes.Count > 1 && Model.IsDefaultSelection)
        {
			<div class="btn-group pull-right">
				<button type="button" class="btn btn-labeled btn-primary" data-toggle="dropdown">
					<span class="btn-label">
						<i class="glyphicon glyphicon-plus"></i>
					</span>@Piranha.Manager.Resources.Global.Add
				</button>
				<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
					<span class="caret"></span>
					<span class="sr-only">Toggle Dropdown</span>
				</button>
				<ul class="dropdown-menu dropdown-menu-right" role="menu">
					@foreach (var type in Model.PageTypes) {
						<li><a href="@Url.Action("Add", new { @type = type.Slug })">@type.Name</a></li>
					}
				</ul>
			</div>
		} else {
            var type = Model.IsDefaultSelection ? Model.PageTypes.FirstOrDefault() : Model.PageTypes.Where(t => t.IsActive).Single();

			<div class="btn-group submit pull-right">
				<a href="@Url.Action("Add", new { @type = type.Slug })" class="btn btn-primary btn-labeled">
					<span class="btn-label">
						<i class="glyphicon glyphicon-plus"></i>
					</span>@Piranha.Manager.Resources.Global.Add
				</a>
			</div>
		}

		<!-- Post type filter -->
		@if (Model.PageTypes.Count > 1)
        {
			<ul class="nav nav-pills">
				<li @(Model.IsDefaultSelection ? "class=active" : "")>
					<a href="@Url.Action("List", new { @slug = "" })">@Piranha.Manager.Resources.Global.All</a>
				</li>
				@foreach (var type in Model.PageTypes)
                {
					<li @(type.IsActive ? "class=active" : "")><a href="@Url.Action("List", new { @slug = type.Slug })">@type.Name</a></li>
				}
			</ul>
			<br />
		}
	</div>
</div>

<!-- Post table -->
<table id="page-list" class="table table-striped table-main">
	<thead>
		<tr>
			<th><span class="sort" data-sort="page-title">@Piranha.Manager.Resources.Global.Title</span></th>
			<th><span class="sort" data-sort="page-type">@Piranha.Manager.Resources.Global.Type</span></th>
			<th class="date"><span class="sort" data-sort="page-updated">@Piranha.Manager.Resources.Global.Updated</span></th>
			<th class="date"><span class="sort" data-sort="page-created">@Piranha.Manager.Resources.Global.Created</span></th>
			<th class="actions one"></th>
		</tr>
	</thead>
	<tbody class="list">
		@foreach (var page in Model.Items) {
			<tr @(!page.Published.HasValue ? "class=unpublished" : "")>
				<td>
					<a class="page-title" href="@Url.Action("Edit", new { id = page.Id })">@page.Title</a>
					<p class="meta">
						@if (page.Published.HasValue) {
							<text>Published: @page.Published.Value.ToString("yyyy-MM-dd")</text>
						} else {
							<text>Unpublished</text>
						}
					</p>
				</td>
				<td class="page-type">@page.Type</td>
				<td class="page-updated">@page.Updated.ToString("yyyy-MM-dd")</td>
				<td class="page-created">@page.Created.ToString("yyyy-MM-dd")</td>
				<td class="actions"><a class="delete" href="@Url.Action("Delete", new { @id = page.Id })"></a></td>
			</tr>
		}
	</tbody>
</table>