Piranha.VNext/Core/Piranha.Manager/Areas/Manager/Controllers/PostMgrController.cs
/*
 * Copyright (c) 2014-2015 Håkan Edling
 *
 * This software may be modified and distributed under the terms
 * of the MIT license.  See the LICENSE file for details.
 * 
 * http://github.com/piranhacms/piranha.vnext
 * 
 */

using System;
using System.Linq;
using System.Web.Mvc;
using Piranha.Manager.Models.Post;

namespace Piranha.Areas.Manager.Controllers
{
	/// <summary>
	/// Controller for managing posts.
	/// </summary>
	[Authorize]
	[RouteArea("Manager", AreaPrefix="manager")]
    public class PostMgrController : ManagerController
    {
		/// <summary>
		/// Gets a list of the currently available posts
		/// </summary>
		/// <returns></returns>
		[Route("posts/{slug?}")]
		public ActionResult List(string slug = null) {
			return View(ListModel.Get(slug));
		}

		[Route("post/add/{type}")]
		public ActionResult Add(string type) {
			var model = new EditModel(api, type);

			ViewBag.Title = String.Format(Piranha.Manager.Resources.Post.AddTitle, model.TypeName);
			return View("Edit", model);
		}

		/// <summary>
		/// Gets the edit view for a new or existing post.
		/// </summary>
		/// <param name="id">The optional id</param>
		/// <returns>The view result</returns>
		[Route("post/edit/{id:Guid}")]
		public ActionResult Edit(Guid id) {
			var model = EditModel.GetById(api, id);

			ViewBag.Title = Piranha.Manager.Resources.Post.EditTitle;
			ViewBag.SubTitle = model.Published.HasValue ? 
				((model.Published.Value > DateTime.Now ? "Schedueled: " : "Published: ") + model.Published.Value.ToString("yyyy-MM-dd")) : "Unpublished";

			return View(model);
		}

		/// <summary>
		/// Saves the given post model.
		/// </summary>
		/// <param name="model">The model</param>
		/// <returns>The redirect result</returns>
		[HttpPost]
		[Route("post/save")]
		[ValidateInput(false)]
		[ValidateAntiForgeryToken]
		public ActionResult Save(EditModel model) {
			if (ModelState.IsValid) {
				model.Save(api);
				IsSaved = true;
				return RedirectToAction("Edit", new { id = model.Id });
			}
			if (model.Id.HasValue)
				ViewBag.Title = Piranha.Manager.Resources.Post.EditTitle;
			else ViewBag.Title = String.Format(Piranha.Manager.Resources.Post.AddTitle, model.TypeName);

			return View("Edit", model);
		}

		/// <summary>
		/// Deletes the post with the given id.
		/// </summary>
		/// <param name="id">The unique id</param>
		/// <returns>The redirect result</returns>
		[Route("post/delete/{id:Guid}")]
		public ActionResult Delete(Guid id) {
			api.Posts.Remove(id);
			api.SaveChanges();

			return RedirectToAction("List");
		}

		/// <summary>
		/// Changes the approval status for the specifed comment.
		/// </summary>
		/// <param name="state">The status</param>
		/// <returns>The partial comment list.</returns>
		[HttpPost]
		[Route("post/comment/approve")]
		public ActionResult CommentApprove(CommentState state) {
			var comment = api.Comments.GetSingle(where: c => c.Id == state.CommentId && c.PostId == state.PostId);

			if (comment != null) {
				comment.IsApproved = state.Status;
				api.SaveChanges();
			}
			return View("Partial/CommentList", api.Comments.Get(where: c => c.PostId == state.PostId)
				.Select(c => new Piranha.Manager.Models.Post.EditModel.CommentListItem() {
					Author = c.Author,
					Body = c.Body,
					Created = c.Created,
					Email = c.Email,
					Id = c.Id,
					IsApproved = c.IsApproved,
					IsSpam = c.IsSpam,
					WebSite = c.WebSite
				}).ToList());
		}

		/// <summary>
		/// Changes the spam status for the specifed comment.
		/// </summary>
		/// <param name="state">The status</param>
		/// <returns>The partial comment list.</returns>
		[HttpPost]
		[Route("post/comment/spam")]
		public ActionResult CommentSpam(CommentState state) {
			var comment = api.Comments.GetSingle(where: c => c.Id == state.CommentId && c.PostId == state.PostId);

			if (comment != null) {
				comment.IsSpam = state.Status;
				api.SaveChanges();
			}
			return View("Partial/CommentList", api.Comments.Get(where: c => c.PostId == state.PostId)
				.Select(c => new Piranha.Manager.Models.Post.EditModel.CommentListItem() {
					Author = c.Author,
					Body = c.Body,
					Created = c.Created,
					Email = c.Email,
					Id = c.Id,
					IsApproved = c.IsApproved,
					IsSpam = c.IsSpam,
					WebSite = c.WebSite
				}).ToList());
		}
	}
}

Piranha.VNext/Core/Piranha.Manager/Areas/Manager/Views/PostMgr/Edit.cshtml
@model Piranha.Manager.Models.Post.EditModel

@section head {
	<style type="text/css">
		#Excerpt {
			height: 198px;
		}
	</style>
}

@section script {
	@Html.Partial("Partial/Editor")

	<script type="text/javascript">
		$(document).ready(function () {
			// Initialize select2
			var categories = [
				@foreach (var cat in Model.Categories) {
						<text>"@cat.Text",</text>
					}
			];
			$('#SelectedCategories').select2({ tags: categories, placeholder: "Add some categories to your post" });

			// Initialize comments
			var comments = new manager.commentDialog('#comments', '@Url.Content("~/manager/post/comment")', '@Model.Id');

			// Focus the first input box
			$('#Title').focus();
		});

		// Set submit action to publish
		$(document).on('click', '#submit-publish', function () {
			$('#Action').val('@((int)Piranha.Manager.Models.Post.EditModel.SubmitAction.Publish)');
			$('form').submit();
		});

		// Set submit action to upublish
		$(document).on('click', '#submit-unpublish', function () {
			$('#Action').val('@((int)Piranha.Manager.Models.Post.EditModel.SubmitAction.Unpublish)');
			$('form').submit();
		});
	</script>
}

@using (var form = Html.BeginForm("Save", "PostMgr", FormMethod.Post, new { @class = "form", @role = "form" })) {
	@Html.AntiForgeryToken()
	@Html.HiddenFor(m => m.Id)
	@Html.HiddenFor(m => m.TypeId)
	@Html.HiddenFor(m => m.TypeName)
	@Html.HiddenFor(m => m.Action)

	<div class="row">
		<!-- Actions -->
		<div class="col-sm-12 buttons">
			<!-- Settings -->
			<div class="btn-group">
				<button type="button" class="btn btn-labeled btn-primary" data-toggle="modal" data-target="#mdSettings">
					<span class="btn-label">
						<i class="glyphicon glyphicon-cog"></i>
					</span>
					@Piranha.Manager.Resources.Global.Settings
				</button>
			</div>

			<!-- Comments -->
			<div class="btn-group">
				<button type="button" class="btn btn-labeled btn-info" data-toggle="modal" data-target="#mdComments">
					<span class="btn-label">
						<i class="glyphicon glyphicon-comment"></i>
					</span>
					@Piranha.Manager.Resources.Post.Comments
				</button>
			</div>

			<!-- Actions -->
			<div class="btn-group">
				<button type="submit" class="btn btn-labeled btn-success">
					<span class="btn-label">
						<i class="glyphicon glyphicon-ok"></i>
					</span>
					@if (Model.Published.HasValue) {
						@Piranha.Manager.Resources.Post.UpdatePost
					} else {
						@Piranha.Manager.Resources.Global.SaveDraft
					}
				</button>
				<button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
					<span class="caret"></span>
					<span class="sr-only">Toggle Dropdown</span>
				</button>
				<ul class="dropdown-menu dropdown-menu-right" role="menu">
					@if (Model.Published.HasValue) {
						<li><a id="submit-unpublish" href="#">Unpublish</a></li>
					} else {
						<li><a id="submit-publish" href="#">Publish now</a></li>
					}
					<li class="divider"></li>
					<li><a href="@Url.Action("Delete", new { @id = Model.Id })">Delete post</a></li>
				</ul>
			</div>
		</div>

		<div class="col-sm-12">
			<div class="form-group">
				@Html.TextBoxFor(m => m.Title, new { @class = "form-control title", @placeholder = "Your post title" })
				@Html.ValidationMessageFor(m => m.Title)
			</div>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">@Piranha.Manager.Resources.Global.Information</h3>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-sm-8">
					<div class="form-group">
						@Html.TextAreaFor(m => m.Excerpt, new { @rows = 7, @class = "form-control count-me", @placeholder = "Short excerpt" })
						<p><span>@(Model.Excerpt != null ? Model.Excerpt.Length : 0)</span>/512 characters</p>
						@Html.ValidationMessageFor(m => m.Excerpt)
					</div>
				</div>
				<div class="col-sm-4">
					<div class="form-group">
						@Html.DropDownListFor(m => m.AuthorId, Model.Authors, "", new { @class = "form-control meta", @placeholer = "Select author" })
					</div>
					<div class="form-group">
						@Html.TextBoxFor(m => m.Keywords, new { @class = "form-control meta", @placeholder = "Meta keywords" })
						@Html.ValidationMessageFor(m => m.Keywords)
					</div>
					<div class="form-group">
						@Html.TextAreaFor(m => m.Description, new { @rows = 4, @class = "form-control meta count-me", @placeholder = "Meta description" })
						<p class="charcount"><span>@(Model.Description != null ? Model.Description.Length : 0)</span>/255 characters</p>
						@Html.ValidationMessageFor(m => m.Description)
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="form-group">
						@Html.HiddenFor(m => m.SelectedCategories)
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="panel panel-default" role="tabpanel">
		<div class="panel-heading">
			<div role="tablist">

			</div>
			<div class="btn-group pull-right" style="display:none">
				<button type="button" class="btn btn-sm btn-labeled btn-info">
					<span class="btn-label">
						<i class="glyphicon glyphicon-paperclip"></i>
					</span>
					Attachments
				</button>
			</div>
			<button class="btn btn-sm btn-primary pull-right">Main body</button>
			<button class="btn btn-sm btn-primary pull-right" style="display:none">Excerpt</button>
			<h3 class="panel-title">Content</h3>
		</div>
		<div class="panel-body" style="padding:0">
			<div class="form-group" style="border:0">
				@Html.TextAreaFor(m => m.Body, new { @rows = 14, @class = "form-control editor" })
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-12">
		</div>
	</div>

	<!-- Comments modal -->
	<div class="modal fade" id="mdComments" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="myModalLabel">@Piranha.Manager.Resources.Post.Comments</h4>
				</div>
				<div id="comments">
					@Html.Partial("Partial/CommentList", Model.Comments)
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">@Piranha.Manager.Resources.Global.Ok</button>
				</div>
			</div>
		</div>
	</div>

	<!-- Settings modal -->
	<div class="modal fade" id="mdSettings" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="myModalLabel">Post settings</h4>
				</div>
				<div class="modal-body">
					@Html.LabelFor(m => m.Slug, Piranha.Manager.Resources.Global.Slug)
					<div class="form-group">
						@Html.TextBoxFor(m => m.Slug, new { @class = "form-control meta", @placeholder = "A slug will be generated automatically" })
					</div>
					@Html.LabelFor(m => m.Route, Piranha.Manager.Resources.Global.Route)
					<div class="form-group">
						@Html.TextBoxFor(m => m.Route, new { @class = "form-control meta", @placeholder = "Add optional route" })
					</div>
					@Html.LabelFor(m => m.View, Piranha.Manager.Resources.Global.View)
					<div class="form-group">
						@Html.TextBoxFor(m => m.View, new { @class = "form-control meta", @placeholder = "Add optional view" })
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">@Piranha.Manager.Resources.Global.Ok</button>
				</div>
			</div>
		</div>
	</div>
}

Piranha.VNext/Core/Piranha.Manager/Areas/Manager/Views/PostMgr/List.cshtml
@model Piranha.Manager.Models.Post.ListModel
@{
	ViewBag.Title = Piranha.Manager.Resources.Post.ListTitle;
}
@section script {
	<script type="text/javascript">
		var options = {
			valueNames: ['post-title', 'post-type', 'post-updated', 'post-created']
		};
		var postList = new List('post-list', options);
	</script>
}

<div class="row">
	<div class="col-sm-12 @(Model.PostTypes.Count == 1 ? "buttons" : "")">
		@if (Model.PostTypes.Count > 1 && Model.IsDefaultSelection) {
			<div class="btn-group pull-right">
				<button type="button" class="btn btn-labeled btn-primary" data-toggle="dropdown">
					<span class="btn-label">
						<i class="glyphicon glyphicon-plus"></i>
					</span>@Piranha.Manager.Resources.Global.Add
				</button>
				<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
					<span class="caret"></span>
					<span class="sr-only">Toggle Dropdown</span>
				</button>
				<ul class="dropdown-menu dropdown-menu-right" role="menu">
					@foreach (var type in Model.PostTypes) {
						<li><a href="@Url.Action("Add", new { @type = type.Slug })">@type.Name</a></li>
					}
				</ul>
			</div>
		} else {
			var type = Model.IsDefaultSelection ? Model.PostTypes.FirstOrDefault() : Model.PostTypes.Where(t => t.IsActive).Single();

			<div class="btn-group submit pull-right">
				<a href="@Url.Action("Add", new { @type = type.Slug })" class="btn btn-primary btn-labeled">
					<span class="btn-label">
						<i class="glyphicon glyphicon-plus"></i>
					</span>@Piranha.Manager.Resources.Global.Add
				</a>
			</div>
		}

		<!-- Post type filter -->
		@if (Model.PostTypes.Count > 1) {
			<ul class="nav nav-pills">
				<li @(Model.IsDefaultSelection ? "class=active" : "")>
					<a href="@Url.Action("List", new { @slug = "" })">@Piranha.Manager.Resources.Global.All</a>
				</li>
				@foreach (var type in Model.PostTypes) {
					<li @(type.IsActive ? "class=active" : "")><a href="@Url.Action("List", new { @slug = type.Slug })">@type.Name</a></li>
				}
			</ul>
			<br />
		}
	</div>
</div>

<!-- Post table -->
<table id="post-list" class="table table-striped table-main">
	<thead>
		<tr>
			<th><span class="sort" data-sort="post-title">@Piranha.Manager.Resources.Global.Title</span></th>
			<th><span class="sort" data-sort="post-type">@Piranha.Manager.Resources.Global.Type</span></th>
			<th class="date"><span class="sort" data-sort="post-updated">@Piranha.Manager.Resources.Global.Updated</span></th>
			<th class="date"><span class="sort" data-sort="post-created">@Piranha.Manager.Resources.Global.Created</span></th>
			<th class="actions one"></th>
		</tr>
	</thead>
	<tbody class="list">
		@foreach (var post in Model.Items) {
			<tr @(!post.Published.HasValue ? "class=unpublished" : "")>
				<td>
					<a class="post-title" href="@Url.Action("Edit", new { id = post.Id })">@post.Title</a>
					<p class="meta">
						@if (post.Published.HasValue) {
							<text>Published: @post.Published.Value.ToString("yyyy-MM-dd")</text>
						} else {
							<text>Unpublished</text>
						}
					</p>
				</td>
				<td class="post-type">@post.Type</td>
				<td class="post-updated">@post.Updated.ToString("yyyy-MM-dd")</td>
				<td class="post-created">@post.Created.ToString("yyyy-MM-dd")</td>
				<td class="actions"><a class="delete" href="@Url.Action("Delete", new { @id = post.Id })"></a></td>
			</tr>
		}
	</tbody>
</table>


